### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#35]
- [x] Martinův review #13
- [x] uklidit dependencies #36
- [x] id projektu v testech #37
- [x] upgrade na Node 8 #38
- [x] upgrade Webpacku (a případně dalších závislostí?) #39
- [x] `ACCOUNT_ID` env vypadá nepoužitě
- [x] jak se reportují chyby?

S dalším bych počkal až tohle upravíš.

**Comment by MiroCillik** [comment]
S tym `ACCOUNT_ID` mas asi pravdu.. Zaujimave, som si bol isty, ze sa to tam na nieco pouziva :/ Ale skusam to bez toho a zda sa, ze to funguje.

Ako to myslis s tym reportovanim chyb? Ako to mas ty u Dev Portalu a GD provisioningu? :)

**Comment by JakubMatejka** [comment]
A jo, tak pak ti chybí v `serverless.yml` (https://github.com/keboola/developer-portal/blob/master/serverless.yml#L18), takže se ten logger vůbec nedeployne.

**Comment by MiroCillik** [comment]
Aha, ok, mrknem na to.

**Comment by MiroCillik** [comment]
Odstranene ACCOUNT_ID: https://github.com/keboola/oauth-api/pull/43

Pridany Papertrail plugin: https://github.com/keboola/oauth-api/pull/44

**Comment by MiroCillik** [comment]
Mozes zacat druhe kolo review :)

**Comment by JakubMatejka** [comment]
Hm, nejde mi stáhnout jdk ;o(
![oauth-api zsh 2018-07-31 14-53-20](https://user-images.githubusercontent.com/215660/43460633-79e7f062-94d1-11e8-80c8-4bf49b133e8d.png)

**Comment by pivnicek** [comment]
oh! I know this one :-D mmt

**Comment by pivnicek** [comment]
Fixed this in the oracle-ex recently:
https://github.com/keboola/db-extractor-oracle/blob/master/Dockerfile#L42

**Comment by MiroCillik** [comment]
@pivnicek Interesting solution :) But it's for Debian and I need this to run on Amazon AMI Linux, which is like Cent OS / RHEL basically. 

I have(hopefully) solved this by installing OpenJDK instead.

**Comment by MiroCillik** [comment]
https://github.com/keboola/oauth-api/pull/46

**Comment by JakubMatejka** [comment]
Tak ještě pár věcí:
- Get on non-existing credentials should return 404 #53
- Create credentials fails #52
- Improve validation messages #49
- Add cors to all endpoints(?) #50
- Convert app secret to base64 #51

**Comment by JakubMatejka** [comment]
Jo a ještě bych udělal upgrade na Node 8

**Comment by MiroCillik** [comment]
https://github.com/keboola/oauth-api/issues/52 je divne, pozriem na to.

Ono uz to je na Node 8, len v serverless.yml mam porad staru verzi :) To myslis?

**Comment by JakubMatejka** [comment]
jj, ten kód by pak v awsku jel na šestce

**Comment by MiroCillik** [comment]
jj, vsimol som si to tam uz predtym, len som to zabudol opravit :)

**Comment by MiroCillik** [comment]
Prva polka fixnuta tu https://github.com/keboola/oauth-api/pull/55

**Comment by MiroCillik** [comment]
Tu by som to zavrel
